export const colleges = {
  100: {
    id: 100,
    name: "College of Liberal Arts",
    departments: [
      {
        _id: "101",
        department: "Department of Chinese Literature",
        name: "Chinese Literature",
        chinese_name: "中文系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=1",
        official_website_url: "https://chinese.nccu.edu.tw/",
        course_map_url:""

      },
      {
        _id: "103",
        department: "Department of History",
        name: "History",
        chinese_name: "歷史系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=2",
        official_website_url: "https://history.nccu.edu.tw/",
      },
      {
        _id: "104",
        department: "Department of Philosophy",
        name: "Philosophy",
        chinese_name: "哲學系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=3",
        official_website_url: "https://thinker.nccu.edu.tw/",
      },
      {
        _id: "100",
        department: "College of Liberal Arts ",
        name: "College of Liberal Arts ",
        chinese_name: "文院學士",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=4",
        official_website_url: "https://la.nccu.edu.tw/",
      },
      {
        _id: "158",
        department: "Graduate Institute of Taiwan History",
        name: "Graduate Institute of Taiwan History",
        chinese_name: "台史所 ",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=5",
        official_website_url: "https://taiwan.nccu.edu.tw/",
        course_map_url:""
      },
      {
        _id: "159",
        department: "Graduate Institute of Taiwanese Literature",
        name: "Graduate Institute of Taiwanese Literature",
        chinese_name: "台文所",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=6",
        official_website_url: "https://tailit.nccu.edu.tw/",
        course_map_url:""
      },
      {
        _id: "156",
        department: "Graduate Institute of Religious Studies",
        name: "Graduate Institute of Religious Studies",
        chinese_name: "宗教所",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=7",
        official_website_url: "https://religion.nccu.edu.tw/",
        course_map_url:""
      },
      {
        _id: "155",
        department: "Graduate Institute of Library, Information and Archival Studies",
        name: "Graduate Institute of Library, Information and Archival Studies",
        chinese_name: "圖檔所",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=8",
        official_website_url: "https://lias.nccu.edu.tw/",
        course_map_url:""
      },
      {
        _id: "913",
        department: "E-learning Master Program of Library and Information Studies",
        name: "E-learning Master Program of Library and Information Studies",
        chinese_name: "圖資專",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=9",
        official_website_url: "https://elis.nccu.edu.tw/",
        course_map_url:""
      },
      {
        _id: "912",
        department:"Master of Chinese Teaching",
        name: "Master of Chinese Teaching",
        chinese_name: "國教碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=9",
        official_website_url: "http://ctma.nccu.edu.tw/",
      },
      {
        _id: "161",
        department: "Master's Program in Teaching Chinese as a Second Language",
        name: "Master's Program in Teaching Chinese as a Second Language",
        chinese_name: "華文碩程",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=10",
        official_website_url: "https://tcsl.nccu.edu.tw/",
        course_map_url:""
      },
      {
        _id: "160",
        department: "Doctor's Program in Teaching Chinese as a Second Language",
        name: "Doctor's Program in Teaching Chinese as a Second Language",
        chinese_name: "華文博",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=1",
        official_website_url: "https://tcsl.nccu.edu.tw/",
        course_map_url:""
      },
    ],
  },
  102: {
    id: 102,
    name: "College of Education",
    departments: [
      {
        _id: "102",
        department:"Department of Education",
        name: "Education",
        chinese_name: "教育系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=5",
        official_website_url: "https://edu.nccu.edu.tw/",
      },
      {
        _id: "900",
        department:"College of Education",
        name: "College of Education",
        chinese_name: "教院",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=5",
        official_website_url: "https://educ.nccu.edu.tw/",
      },
      {
        _id: "911",
        department:"Master of Education in School Administration",
        name: "Master of Education in School Administration",
        chinese_name: "學行碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=6",
        official_website_url: "https://mesa.nccu.edu.tw/",
      },
      {
        _id: "157",
        department:"Graduate Institute of Early Childhood Education",
        name: "Graduate Institute of Early Childhood Education",
        chinese_name: "幼教碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=7",
        official_website_url: "https://ece.nccu.edu.tw/",
      },
      {
        _id: "171",
        department:"Graduate Institute of Educational Administration and Policy",
        name: "Graduate Institute of Educational Administration and Policy",
        chinese_name: "教政碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=8",
        official_website_url: "https://eap.nccu.edu.tw/",
      },
    ],
  },
  200: {
    id: 200,
    name: "College of Politics",
    departments: [
      {
        _id: "202",
        department: "Department of Political Science",
        name: "Political Science",
        chinese_name: "政治系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=2",
        official_website_url: "https://politics.nccu.edu.tw/",
      },
      {
        _id: "204",
        department: "Department of Sociology",
        name: "Sociology",
        chinese_name: "社會系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=3",
        official_website_url: "https://sociology.nccu.edu.tw/",
      },
      {
        _id: "205",
        department: "Department of Public Finance",
        name: "Public Finance",
        chinese_name: "財政系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=4",
        official_website_url: "https://pf.nccu.edu.tw/",
      },
      {
        _id: "206",
        department: "Department of Public Administration",
        name: "Public Administration",
        chinese_name: "公行系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=5",
        official_website_url: "https://pa.nccu.edu.tw/",
      },
      {
        _id: "207",
        department: "Department of Land Economics",
        name: "Land Economics",
        chinese_name: "地政系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=6",
        official_website_url: "https://landeconomics.nccu.edu.tw/",
      },
      {
        _id: "208",
        department: "Department of Economics",
        name: "Economics",
        chinese_name: "經濟系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=7",
        official_website_url: "https://econo.nccu.edu.tw/",
      },
      {
        _id: "209",
        department: "Department of Ethnology",
        name: "Ethnology",
        chinese_name: "民族系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=8",
        official_website_url: "http://www.ethnos.nccu.edu.tw/institute.asp",
      },
      {
        _id: "261",
        department: "Graduate Institute of Development Studies",
        name: "Graduate Institute of Development Studies",
        chinese_name: "國發所",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=9",
        official_website_url: "http://www.ethnos.nccu.edu.tw/institute.asp",
      },
      {
        _id: "262",
        department: "Graduate Institute of Labor Research",
        name: "Graduate Institute of Labor Research",
        chinese_name: "勞工所",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=10",
        official_website_url: "https://labour.nccu.edu.tw/",
      },
      {
        _id: "264",
        department: "The Master Program of Land Economics",
        name: "The Master Program of Land Economics",
        chinese_name: "地政專",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=11",
        official_website_url: "safdsfsdfsdf",
      },
      {
        _id: "267",
        department: "Masters Program in Land Policy and Environmental Planning for Indigenous Peoples",
        name: "Masters Program in Land Policy and Environmental Planning for Indigenous Peoples",
        chinese_name: "原碩專",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=12",
        official_website_url: "http://iland.nccu.edu.tw/",
      },
      {
        _id: "264",
        department: "Graduate Institute of Social Work",
        name: "Graduate Institute of Social Work",
        chinese_name: "社工碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=13",
        official_website_url: "https://socialwork.nccu.edu.tw/",
      },
      {
        _id: "266",
        department: "International Master's Program of Applied Economics and Social Development",
        name: "International Master's Program of Applied Economics and Social Development",
        chinese_name: "應社碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=14",
        official_website_url: "https://internationalprograms.nccu.edu.tw/home-imes/",
      },
      {
        _id: "218",
        department: "Master of Eminent Public Administrators",
        name: "Master of Eminent Public Administrators",
        chinese_name: "行管碩/行國防/行領導",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=15",
        official_website_url: "https://mepa.nccu.edu.tw/",
      },
      {
        _id: "926",
        department: "International Master's Program in Asia-Pacific Studies",
        name: "International Master's Program in Asia-Pacific Studies",
        chinese_name: "亞太碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=16",
        official_website_url: "safdsfsdfsdf",
      },
      {
        _id: "265",
        department: "International Doctoral Program in Asia-Pacific Studies",
        name: "International Doctoral Program in Asia-Pacific Studies",
        chinese_name: "亞太博",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=17",
        official_website_url: "https://internationalprograms.nccu.edu.tw/home-idas/",
      }
    ],
  },
  203: {
      id: 203,
      name: "College of International Affairs",
      departments: 
      [{
        _id: "203",
        department:"Department of Diplomacy",
        name: "Diplomacy",
        chinese_name: "外交系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=18",
        official_website_url: "https://diplomacy.nccu.edu.tw/",
      },
      {
        _id: "800",
        department: "College of International Affairs",
        name: "College of International Affairs",
        chinese_name: "國務院",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=19",
        official_website_url: "https://ocia.nccu.edu.tw/",
      },
      {
        _id: "260",
        department: "Graduate Institute of East Asian Studies",
        name: "Graduate Institute of East Asian Studies",
        chinese_name: "東亞所",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=20",
        official_website_url: "https://eastasia.nccu.edu.tw/",
      },
      {
        _id: "206",
        department: "Master Program in Middle Eastern and Central Asian Studies",
        name: "Master Program in Middle Eastern and Central Asian Studies",
        chinese_name: "中東亞",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=21",
        official_website_url: "https://mecas.nccu.edu.tw/",
      },
      {
        _id: "207",
        department: "Master Program in Strategic and International Studies",
        name: "Master Program in Strategic and International Studies",
        chinese_name: "外戰略",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=22",
        official_website_url: "https://diplomacy.nccu.edu.tw/PageDoc?fid=4848",
      },
      {
        _id: "981",
        department: "Master Program in National Security and Mainland China Studies",
        name: "Master Program in National Security and Mainland China Studies",
        chinese_name: "國安碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=23",
        official_website_url: "https://ocia51113.nccu.edu.tw/",
      },
      {
        _id: "861",
        department: "Master Program in Japan Studies",
        name: "Master Program in Japan Studies",
        chinese_name: "日本碩學程",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=24",
        official_website_url: "asdasdasdasd",
      },
      {
        _id: "863",
        department: "Doctoral Program in Japan Studies",
        name: "Doctoral Program in Japan Studies",
        chinese_name: "日學博",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=25",
        official_website_url: "https://mpjs.nccu.edu.tw/",
      },
    ]
  },
  300: {
    id: 300,
    name: "College of Commerce",
    departments: [
      {
        _id: "301",
        department: "Department of International Business",
        name: "International Business",
        chinese_name: "國貿系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=6",
        official_website_url: "https://ib.nccu.edu.tw/",
      },
      {
        _id: "302",
        department: "Department of Money and Banking",
        name: "Money and Banking",
        chinese_name: "金融系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=4",
        official_website_url: "https://banking.nccu.edu.tw/",
      },
      {
        _id: "303",
        department: "Department of Accounting",
        name: "Accounting",
        chinese_name: "會計系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=15",
        official_website_url: "https://acct.nccu.edu.tw/",
      },
      {
        _id: "304",
        department: "Department of Statistics",
        name: "Statistics",
        chinese_name: "統計系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=10",
        official_website_url: "",
      },
      {
        _id: "305",
        department: "Department of Business Administration",
        name: "Business Administration",
        chinese_name: "企管系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=17",
        official_website_url: "http://www.ba.nccu.edu.tw/",
      },
      {
        _id: "306",
        department: "Department of Management Information Systems",
        name: "Management Information Systems",
        chinese_name: "資管系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=18",
        official_website_url: "https://mis2.nccu.edu.tw/",
      },
      {
        _id: "307",
        department: "Department of Finance",
        name: "Finance",
        chinese_name: "財管系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=19",
        official_website_url: "https://finance.nccu.edu.tw/",
      },
      {
        _id: "308",
        department: "Department of Risk Management and Insurance",
        name: "Risk Management and Insurance",
        chinese_name: "風管系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=21",
        official_website_url: "https://rmi.nccu.edu.tw/",
      },
      {
        _id: "300",
        department: "College of Commerce",
        name: "College of Commerce",
        chinese_name: "商院學士",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=22",
        official_website_url: "https://commerce.nccu.edu.tw/",
      },
      {
        _id: "364",
        department: "Graduate Institute of Technology, Innovation and Intellectual Property Management",
        name: "Graduate Institute of Technology, Innovation and Intellectual Property Management",
        chinese_name: "科管智財所",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=23",
        official_website_url: "https://tiipm.nccu.edu.tw/",
      },
      {
        _id: "363",
        department: "Master of Business Administration Program",
        name: "Master of Business Administration Program",
        chinese_name: "企研碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=24",
        official_website_url: "https://mba.nccu.edu.tw/",
      },
      {
        _id: "933",
        department: "International Master of Business Administration",
        name: "International Master of Business Administration",
        chinese_name: "國營碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=25",
        official_website_url: "https://imba.nccu.edu.tw/",
      },
    ],
  },
  400: {
    id: 400,
    name: "College of Communication",
    departments: [
      {
        _id: "401",
        department: "Department of Journalism",
        name: "Journalism",
        chinese_name: "新聞系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=26",
        official_website_url: "",
      },
      {
        _id: "402",
        department: "Department of Advertising",
        name: "Advertising",
        chinese_name: "廣告系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=28",
        official_website_url: "https://ad.nccu.edu.tw/",
      },
      {
        _id: "403",
        department: "Department of Radio & Television",
        name: "Radio & Television",
        chinese_name: "廣電系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=29",
        official_website_url: "https://rtv.nccu.edu.tw/",
      },
      {
        _id: "405",
        department: "Undeclared Major in College of Communication",
        name: "Undeclared Major in College of Communication",
        chinese_name: "傳院",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=10",
        official_website_url: "https://comm.nccu.edu.tw/",
      },
      {
        _id: "406",
        department: "College of Communication",
        name: "College of Communication",
        chinese_name: "傳播學程",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=11",
        official_website_url: "https://comm.nccu.edu.tw/",
      },
      {
        _id: "462",
        department: "Graduate Program in  Digital Content and Technologies",
        name: "Graduate Program in  Digital Content and Technologies",
        chinese_name: "數位碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=12",
        official_website_url: "https://www.dct.nccu.edu.tw/",
      },
      {
        _id: "464",
        department: "International Master's Program in International Communication Studies",
        name: "International Master's Program in International Communication Studies",
        chinese_name: "國傳碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=13",
        official_website_url: "https://imics.nccu.edu.tw/",
      },
      {
        _id: "941",
        department: "M.A. Program in Communication",
        name: "M.A. Program in Communication",
        chinese_name: "傳在碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=14",
        official_website_url: "https://ema.comm.nccu.edu.tw/",
      },
      {
        _id: "463",
        department: "Ph.D Program in Communication",
        name: "Ph.D Program in Communication",
        chinese_name: "傳播博",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=25",
        official_website_url: "https://ccphd.nccu.edu.tw/",
      },
    ],
  },
  500: {
    id: 500,
    name: "College of Foreign Languages",
    departments: [
      {
        _id: "501",
        department: "Department of English",
        name: "English",
        chinese_name: "英文系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=26",
        official_website_url: "https://english.nccu.edu.tw/",
      },
      {
        _id: "502",
        department: "Department of Arabic Language and Culture",
        name: "Arabic Language and Culture",
        chinese_name: "阿語系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=27",
        official_website_url: "https://arabic.nccu.edu.tw/",
      },
      {
        _id: "504",
        department: "Department of Slavic Languages and Literatures",
        name: "Slavic Languages and Literatures",
        chinese_name: "斯語系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=28",
        official_website_url: "https://slavic.nccu.edu.tw/",
      },
      {
        _id: "506",
        department: "Department of Japanese",
        name: "Japanese",
        chinese_name: "日語系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=30",
        official_website_url: "https://japanese.nccu.edu.tw/",
      },
      {
        _id: "507",
        department: "Department of Korean Language and Culture",
        name: "Korean Language and Culture",
        chinese_name: "韓文系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=31",
        official_website_url: "https://korean.nccu.edu.tw/",
      },
      {
        _id: "508",
        department: "Department of Turkish Language and Culture",
        name: "Turkish Language and Culture",
        chinese_name: "土語系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=32",
        official_website_url: "https://turkish.nccu.edu.tw/",
      },
      {
        _id: "509",
        department: "Department of European Languages and Cultures",
        name: "Department of European Languages and Cultures",
        chinese_name: "歐文學系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=33",
        official_website_url: "https://european.nccu.edu.tw/",
      },
      {
        _id: "510",
        department: "College of Foreign Languages",
        name: "College of Foreign Languages",
        chinese_name: "外院學士",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=34",
        official_website_url: "https://foreign.nccu.edu.tw/",
      },    
      {
        _id: "560",
        department: "Master Program in Middle Eastern and Central Asian Studies",
        name: "Master Program in Middle Eastern and Central Asian Studies",
        chinese_name: "中東亞學程",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=35",
        official_website_url: "https://mecas.nccu.edu.tw/",
      },
      {
        _id: "510",
        department: "Program in Southeast Asian Languages and Cultures",
        name: "Program in Southeast Asian Languages and Cultures",
        chinese_name: "東南亞語言與文化學士學位學程",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=36",
        official_website_url: "https://sealc.nccu.edu.tw/",
      },
      {
        _id: "555",
        department: "Graduate Institute of Linguistics",
        name: "Graduate Institute of Linguistics",
        chinese_name: "語言所",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=37",
        official_website_url: "https://ling.nccu.edu.tw/",
      },
      {
        _id: "951",
        department: "M.A.Program in TESOL for In-Service Teachers",
        name: "M.A.Program in TESOL for In-Service Teachers",
        chinese_name: "英教碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=38",
        official_website_url: "https://etma.nccu.edu.tw/",
      },
      {
        _id: "5T1",
        department: "Foreign Languages Center",
        name: "Foreign Languages Center",
        chinese_name: "外文中心",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=39",
        official_website_url: "https://flc.nccu.edu.tw/",
      },
    ],    
  },
  600: {
    id: 600,
    name: "College of Law",
    departments: [
      {
        _id: "601",
        department: "Department of Law",
        name: "Law",
        chinese_name: "法律系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=40",
        official_website_url: "http://www.law.nccu.edu.tw/",
      },
      {
        _id: "600",
        department: "College of Law",
        name: "Law",
        chinese_name: "法學院",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=41",
        official_website_url: "http://www.law.nccu.edu.tw/",
      },
      {
        _id: "961",
        department: "Executive Master of Laws Program",
        name: "Executive Master of Laws Program",
        chinese_name: "法碩專",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=42",
        official_website_url: "http://www.law.nccu.edu.tw/zh_tw/departments/master/Special_introduction",
      },
      {
        _id: "604",
        department: "Graduate Institute of Law and Interdisciplinary Studies",
        name: "Graduate Institute of Law and Interdisciplinary Studies",
        chinese_name: "法科碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=43",
        official_website_url: "http://www.law.nccu.edu.tw/zh_tw/departments/Inter_discipline/Law_Institute",
      }
    ],
  },
  700: {
    id: 700,
    name: "College of Science",
    departments: [
      {
        _id: "701",
        department: "Department of Mathematical Sciences",
        name: "Mathematical Sciences",
        chinese_name: "應數系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=44",
        official_website_url: "https://math.nccu.edu.tw/",
      },
      {
        _id: "702",
        department: "Department of Psychology",
        name: "Psychology",
        chinese_name: "心理系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=45",
        official_website_url: "https://psy.nccu.edu.tw/",
      },
      {
        _id: "782",
        department: "Bachelor of Science(B.S.) Program in Electrophysics",
        name: "Bachelor of Science(B.S.) Program in Electrophysics",
        chinese_name: "電物學程",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=46",
        official_website_url: "https://ephys.nccu.edu.tw/",
      },
      {
        _id: "705",
        department: "Graduate Institute of Applied Physics",
        name: "Graduate Institute of Applied Physics",
        chinese_name: "應物所",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=47",
        official_website_url: "https://phys.nccu.edu.tw/",
      },
      {
        _id: "754",
        department: "Graduate Institute of Neuroscience",
        name: "Graduate Institute of Neuroscience",
        chinese_name: "神科所",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=48",
        official_website_url: "https://in.nccu.edu.tw/",
      },
      {
        _id: "172",
        department: "MA Program of Counseling and Guidance",
        name: "MA Program of Counseling and Guidance",
        chinese_name: "輔諮碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=49",
        official_website_url: "https://mpcg.nccu.edu.tw/",
      },
    ],
  },
  703: {
    id: 102,
    name: "College of Informatics",
    departments: [
      {
        _id: "703",
        department: "Department of Computer Science",
        name: "Computer Science",
        chinese_name: "資科系",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=50",
        official_website_url: "https://www.cs.nccu.edu.tw/web/index/index.jsp",
      },
      {
        _id: "781",
        department: "Undergraduate Program in Digital Content and Technologies",
        name: "Undergraduate Program in Digital Content and Technologies",
        chinese_name: "數位學程",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=51",
        official_website_url: "https://dct.nccu.edu.tw/",
      },
      {
        _id: "ZA0",
        department: "College of Informatics",
        name: "College of Informatics",
        chinese_name: "資訊學院",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=3",
        official_website_url: "https://www.cs.nccu.edu.tw/web/index/index.jsp",
      },
      {
        _id: "971",
        department: "Master Program in Computer Science",
        name: "Master Program in Computer Science",
        chinese_name: "資專碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=4",
        official_website_url: "https://www.cs.nccu.edu.tw/web/about/about.jsp?cp_no=CP1558925060196",
      },
      {
        _id: "761",
        department: "Social Networks and Human-Centered Computing (SNHCC)",
        name: "Social Networks and Human-Centered Computing (SNHCC)",
        chinese_name: "群智博",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=5",
        official_website_url: "https://tigp.sinica.edu.tw/",
      },
    ],
  },
  1100: {
    id: 1100,
    name: "International College of Innovation",
    departments: [
      {
        _id: "Z23",
        department: "International College of Innovation",
        name: "International College of Innovation",
        chinese_name: "創國學院",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=6",
        official_website_url: "https://ici.nccu.edu.tw/",
      },
      {
        _id: "ZU1",
        department: "BA in Global Governance",
        name: "BA in Global Governance",
        chinese_name: "創新國際事務學院",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=7",
        official_website_url: "https://ici.nccu.edu.tw/",
      },
    ],
  },
  1200: {
    id: 1200,
    name: "Other",
    departments: [
      {
        _id: "1201",
        department: "Center for Creativity and Innovation Studies",
        name: "Center for Creativity and Innovation Studies",
        chinese_name: "創新創造力研究中心",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=8",
        official_website_url: "http://www.ccis.nccu.edu.tw/",
      },
      {
        _id: "1202",
        department: "Office of Academic Affairs Center of General Education",
        name: "Office of Academic Affairs Center of General Education",
        chinese_name: "教務處通識教育中心",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=9",
        official_website_url: "https://aca.nccu.edu.tw/zh/%E9%80%9A%E8%AD%98%E6%95%99%E8%82%B2%E4%B8%AD%E5%BF%83",
      },
      {
        _id: "1203",
        department: "International Relation(Common Course)",
        name: "International Relation(Common Course)",
        chinese_name: "國關通",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=10",
        official_website_url: "https://iir.nccu.edu.tw/",
      },
      {
        _id: "1204",
        department: "Program in Bio-technology Management",
        name: "Program in Bio-technology Management",
        chinese_name: "生科程碩",
        logo_img_url: "https://source.unsplash.com/random/200x200?sig=81",
        official_website_url: "https://tiipm.nccu.edu.tw/zh_tw/BMP",
      },
    ],
  },
};

export const departmentsData=[
  {
    _id: "101",
    department: "Department of Chinese Literature",
    name: "CHINESE",
    chinese_name: "中文系",
    logo_img_url: "https://source.unsplash.com/random/200x200?sig=1",
        official_website_url: "",
  },
  {
    _id: "103",
    department: "Department of History",
    name: "HISTORY",
    chinese_name: "歷史系",
  },
  {
    _id: "104",
    department: "Department of Philosophy",
    name: "PHILOSOPHY",
    chinese_name: "哲學系",
  },
  {
    _id: "102",
    department:"Department of Education",
    name: "EDUACATION",
    chinese_name: "教育系",
  },
  {
    _id: "202",
    department: "Department of Political Science",
    name: "ENGLISH",
    chinese_name: "政治系",
  },
  {
    _id: "204",
    department: "Department of Sociology",
    name: "ARABIC",
    chinese_name: "社會系",
  },
  {
    _id: "205",
    department: "Department of Public Finance",
    name: "FINANCE",
    chinese_name: "財政系",
  },
  {
    _id: "206",
    department: "Department of Public Administration",
    name: "JAPANESE",
    chinese_name: "公行系",
  },
  {
    _id: "207",
    department: "Department of Land Economics",
    name: "KOREA",
    chinese_name: "地政系",
  },
  {
    _id: "208",
    department: "Department of Economics",
    name: "KOREA",
    chinese_name: "經濟系",
  },
  {
    _id: "209",
    department: "Department of Ethnology",
    name: "KOREA",
    chinese_name: "民族系",
  },
  {
    _id: "203",
    department:"Department of Diplomacy",
    name: "LAW",
    chinese_name: "外交系",
  },
  {
    _id: "301",
    department: "Department of International Business",
    name: "ENGLISH",
    chinese_name: "國貿系",
  },
  {
    _id: "302",
    department: "Department of Money and Banking",
    name: "ARABIC",
    chinese_name: "金融系",
  },
  {
    _id: "303",
    department: "Department of Accounting",
    name: "FINANCE",
    chinese_name: "會計系",
  },
  {
    _id: "304",
    department: "Department of Statistics",
    name: "Department of Statistics",
    chinese_name: "統計系",
  },
  {
    _id: "305",
    department: "Department of Business Administration",
    name: "Department of Business Administration",
    chinese_name: "企管系",
  },
  {
    _id: "306",
    department: "Department of Management Information Systems",
    name: "Department of Management Information Systems",
    chinese_name: "資管系",
  },
  {
    _id: "307",
    department: "Department of Finance",
    name: "Department of Finance",
    chinese_name: "財管系",
  },
  {
    _id: "308",
    department: "Department of Risk Management and Insurance",
    name: "Department of Risk Management and Insurance",
    chinese_name: "風管系",
  },
  {
    _id: "401",
    department: "Department of Journalism",
    name: "Department of Journalism",
    chinese_name: "新聞系",
  },
  {
    _id: "402",
    department: "Department of Advertising",
    name: "Department of Advertising",
    chinese_name: "廣告系",
  },
  {
    _id: "403",
    department: "Department of Radio & Television",
    name: "Department of Radio & Television",
    chinese_name: "廣電系",
  },
  {
    _id: "404",
    department: "ENGLISH",
    name: "ENGLISH",
    chinese_name: "傳播學程",
  },
  {
    _id: "501",
    department: "Department of English",
    name: "Department of English",
    chinese_name: "英文系",
  },
  {
    _id: "502",
    department: "Department of Arabic Language and Culture",
    name: "Department of Arabic Language and Culture",
    chinese_name: "阿語系",
  },
  {
    _id: "504",
    department: "Department of Slavic Languages and Literatures",
    name: "Department of Slavic Languages and Literatures",
    chinese_name: "斯語系",
  },
  {
    _id: "508",
    department: "Department of Arabic Language and Culture                                                                                             ",
    name: "Department of Arabic Language and Culture                                                                                             ",
    chinese_name: "土語系",
  },
  {
    _id: "601",
    department: "College of Law",
    name: "LAW",
    chinese_name: "法律系",
  },
  {
    _id: "506",
    department: "Department of Japanese",
    name: "Department of Japanese",
    chinese_name: "日語系",
  },
  {
    _id: "507",
    department: "Department of Korean Language and Culture",
    name: "Department of Korean Language and Culture",
    chinese_name: "韓文系",
  },
  {
    _id: "601",
    department: "Department of Law",
    name: "LAW",
    chinese_name: "法律系",
  },
  {
    _id: "602",
    department: "College of Law",
    name: "LAW",
    chinese_name: "法學院",
  },
  {
    _id: "701",
    department: "Department of Mathematical Sciences",
    name: "Mathematical Sciences",
    chinese_name: "應數系",
  },
  {
    _id: "702",
    department: "Department of Psychology",
    name: "Department of Psychology",
    chinese_name: "心理系",
  },
  {
    _id: "703",
    department: "Department of Computer Science",
    name: "Department of Computer Science",
    chinese_name: "資科系",
  }
]